global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "gnmic"
    static_configs:
      - targets: ["gnmic:9804"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
